### ISSUE TITLE
Save clusters found with mouse tracking

### ISSUE THREAD

**Issue by felipemfp** [GeoGuideProject/geoguide#10]
The idea is to have a history of clusters for each dataset per user.

That way we can analyse the user's interests and make better suggestions (improve IUGA algorithm).

__TODO__

- [x] Send the clusters from client to server (@chicobentojr; @tiagolisboa)
- [x] Persist on PostGIS (@felipemfp; @tiagolisboa)
- [x] Improve IUGA algorithm
